### ISSUE TITLE
add option to enable/disable screen saver

### ISSUE THREAD

**Issue by beta-tester** [raspberrypi-ui/rc_gui#22]
please add an advanced option to enable/disable screen saver for desktop and for terminal console.
i always prefer to have my desktop and/or terminal console visible on my monitor, even when i am away from keyboard and mouse. i hate, when my monitor goes blank and off in the raspbian default settings, and i always struggling with finding the right place to set screen saver permanently off.

or would it be a feature request for raspi-config?

**Comment by ZanderBrown** [comment]
I think this could be hard to implement as Raspbian doesn't have a screen saver as such simply x times out. A quick fix for you is to install xscreensaver and set It to disabled.

**Comment by andrum99** [comment]
Fixed by https://github.com/raspberrypi-ui/rc_gui/commit/bdf74e0f2e115eeee2628ad94be0db8082c6e58b#diff-14f5ca818ffb1f5c9c2f924c5e54ac45.

(`raspi-config` also now has this capability, since https://github.com/RPi-Distro/raspi-config/pull/103).

**Comment by beta-tester** [comment]
thank you!
