### ISSUE TITLE
changed keyboard layout in x window does not survive reboots in stretch

### ISSUE THREAD

**Issue by cwacha** [raspberrypi-ui/rc_gui#37]
A changed keyboard mapping using the GUI tools or via the command line using `raspi-config` gets correctly saved in the `/etc/defaults` directory and applied to both the command line and the currently running x window system. 

# Issue
After a reboot the mapping in the x window system is again set to the distro default of United Kingdom / English (UK). It ignores the setting saved in `/etc/defaults`. The command line (i.e. as switched to using Ctrl-Alt-F1) is showing the correct mapping.
This appeared in the current version 9 (stretch) as downloaded from the website in Dec 17 plus apt-get update and upgrade in late Dec 17.
Even a restart of the x window system using `sudo /etc/init.d/lightdm restart` does not restore the configured keyboard settings.

# Expected Behavior
A user configured keyboard mapping through `raspi-config` or the GUI tools should be restored after a reboot in the x window system automatically. A wrong keyboard mapping is extremely annoying and will reduce the user experience for all non-UK based Raspberry Pi users.

# Workaround
The setting needs to be reapplied using `setxbmap XX` or `lxkeymap` which resolves the issue. But the command needs to be repeated each time the raspberry pi is rebooted.

**Comment by XECDesign** [comment]
Instead of using the system settings, the desktop is using lxkeymap. The simplest thing to do is to run lxkeymap and select the keymap you'd like to use.

**Comment by spl237** [comment]
The latest version of rc_gui now sets the keyboard in /etc/default/keyboard, so this should now be fixed.
