### ISSUE TITLE
Disabling IPv6 via GUI has no effect

### ISSUE THREAD

**Issue by tigran123** [raspberrypi-ui/rc_gui#40]
I have disabled ipv6 via GUI "Wireless & Wired Network Settings", but it is still enabled:

```
$ ifconfig | grep inet6
        inet6 fe80::ba27:ebff:fef8:f5d6  prefixlen 64  scopeid 0x20<link>
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
$ lsmod | grep ipv6
ipv6                  408900  38
```

**Comment by spl237** [comment]
That doesn't disable IPv6 completely, so I'd expect the ipv6 module to stay loaded. 

What it does is to pass the noipv6 parameter to the underlying dhcpcd implementation - see https://jlk.fjfi.cvut.cz/arch/manpages/man/dhcpcd.conf.5 for details.

If dhcpcd isn't correctly responding to that flag, I'd suggest raising an issue with the author of dhcpcd - we take it as-is from the Debian repo.

**Comment by tigran123** [comment]
I managed to disable it by adding these to `/etc/sysctl.conf`:

```
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
```
