### ISSUE TITLE
Serial Port

### ISSUE THREAD

**Issue by bsimmo** [raspberrypi-ui/rc_gui#43]
Just checking (this is the GUI desktop version of raspi-config, taken a while to find)
I've reported on the forum before a few times.

The GUI for serial options does not set thing up properly.
It does not ask the two questions
Console yes/no
Serial port yes/no

So at the moment it just turns UART in config.txt on/off 
but does not add/remove the console=xxxx line from cmdline.txt.

This has created a few help problems for GUI users and setting up devices, e.g. GPS and then getting in a mess with settings.

Can we have it fixed to match please :-)

**Comment by spl237** [comment]
This has been discussed in some detail in the past, when someone raised the same issue, and there was some reason why we chose to leave things as they were. I'm currently trying to find the discussion so I can remind myself of the reasoning before we look at it again... ;)

**Comment by bsimmo** [comment]
Maybe it was me, but I don't remember doing it.
I did bring something up and it was to alter the layout a but, I remember
the outcome being it needed mirror raspi-config so wouldn't be done.

Which in this case this option does not mirror raspi-config.
I looked through the closed cases and couldn't see anything before posting.

Either way, it doesn't mirror raspi-config and it causes problems, leaving
it in a  state with UART enabled yet garbage coming though it due to the
console option still being enabled.
Meaning they then need to reset it and use raspi-config or manually edit it.
:-)

**Comment by spl237** [comment]
No, the previous discussion was on this exact point - you are correct that the GUI does not mirror raspi-config, and the discussion was whether we should expose the same pair of options through the GUI.

I just want to remind myself of why we made the decision previously before changing it!

**Comment by spl237** [comment]
Previous discussion here - https://github.com/RPi-Distro/raspi-config/issues/29

**Comment by bsimmo** [comment]
I've just read that and cannot see your logic of leaving it as is.
There are only two setups I know people use.
The default as it comes no UART, but console. (Never used this setup myself
that I know of)

And everyone else to use UART devices on dev/serial0, be it gps or
whatever, the forum has plenty of these questions.

Nobody I know or have seen wants to enable uart on serial0 and have garbage
come though as it cannot be used.

Who uses it in this messed up state?

I do believe ttyAMC0 that is mentioned  is USB so has nothing to do with it?

UART is ttyS0 and ttyAMA0 with serial0 and serial1 depending on config and
board.


Also as a side, I think we need to disable/enable the getty services and
they are not stopped in either as well?
(In either programmes)
I just know I have to do it, without full understanding on that.

**Comment by XECDesign** [comment]
Well, those pins can be used for 3 setups
1) GPIO
2) Serial with console
3) Serial for something else

> Nobody I know or have seen wants to enable uart on serial0 and have garbage come though as it cannot be used.

2 is the default but, the clock issue on pi 3 B/B+ scrambles that data.

2 makes sense, since it would allow non pi 3 users to connect to the pi quite easily, and it doesn't impact performance for pi 3 users. Unfortunately, it does mean that those pins spit out garbage by default in some cases.

There's no perfect default in this case. You balance one thing versus another.

> Also as a side, I think we need to disable/enable the getty services and they are not stopped in either as well?

SystemD's getty service is dynamically generated and doesn't run on serial unless they're in cmdline.txt (which raspi-config removes).

**Comment by bsimmo** [comment]
What works nicely for everyone are the options we have in raspi-config.
What doesn't work nicely are the options we have in Desktop Config.

Hence they should be in Desktop Config and hence my original post.


Sorry, I i think I should have said.
The UART is locked out if you use the Desktop Setup to enable the serial,
since it does not release it from the console in cmdline.txt

Or..
I use A+, 2B, 3B's and the Zero family.
I can setup serial from raspi-config on all, i cannot front the desktop
config.
I use to many Pi, it gets confusing, lol.

Please if you have time or anyone that can.
Test the current setup on the A+/Zero/2B
And then test 3B/+/ZeroW
and tell me is the desktop setting is satisfactory compared to raspi-config.

(Aka I can't see why you have it in one working nicely and not the other.)

It's getting late and it's Sunday.
Something for next week or so.

I could go through the itterations if you want.


But as far as I remember.
Bitd. All the serial setting did was remove console from cmdline.txt.
Hence GPS would then work on ttyAMA0
Then the Pi3 came along and altered simplicity and uses ttyS0
After a bit thing where sorted with uart= in config.txt and now serial0
points to the gpio's

The extra setting was added and split with (dis)enable serial, and the
other for (did)enable console.

But Desktop does not but for some reason just does enable_uart=1 but
nothing with cmdline.txt
This bit works for neither Pi to get serial output?

**Comment by bsimmo** [comment]
i just tested on a Pi3+
Fresh install

Desktop

Default (State(2))
No entry in config.txt (so serial_uart=0)
console=serial0 in cmdline.txt

Goto Interfaces Serial
Tick enable -ok
Gives
enable_uart=1 in config.txt
console=serial0... Left in cmdline.txt
(A Bad state, serial0 if you try to use it)
(State 4?)

Then Goto Interfaces Serial
Tick enable -ok

enable_uart=0 (also default) in config.txt
console=serial0.. removed from cmdline.txt
(State 1)
So now in a third state, it didn't reverse the previous change.

It then toggles between these two states.

You cannot get a UART only state or back to default state.

**Comment by bsimmo** [comment]
(That option should have said tick disable)

ZeroW behaves the same as Pi3B+


Now an A+ (incl Zero)

It see default state as Enabled (ZeroW/Pi3 see it as Disabled)

Select disable sets
+ serial_uart=0
- console=serial0    (it's removed)

Select enable
~ serial_uart=1 (it's changed)
+ console=serial0 (It's added back)

And switches between these two states.

Now does that look correct to you, it does not to me.
Raspberry Pi Configuration. Please check it :-)

**Comment by spl237** [comment]
There are two switches which control serial, and two settings for each.

There is a serial interface, which can be enabled or disabled, and there is a serial login shell, which can be enabled or disabled.

Having the login shell enabled is pointless if the interface is disabled, so there are three possible states.

1) Serial interface disabled, serial login shell disabled
2) Serial interface enabled, serial login shell enabled
3) Serial interface enabled, serial login shell disabled

With raspi-config, you can select any of those three states. With the GUI, you can only select between the first two states. So at present, the GUI switches 1<->2.

Can you please explain which of 1<->3 and 2<->3 you think is a more sensible switching option for the GUI than this, and why? The purpose of the switch in the GUI is to enable the serial login console, as is stated by the tooltip on the radio buttons. You seem to want an option to enable the serial interface without enabling the console - while I can see that this is useful in some circumstances, it is an additional option, not a justification for stating that the current behaviour is broken or wrong.

**Comment by bsimmo** [comment]
I have stated it above, but may be something for the wider community.

It should and you also mentioned in other threads, it should mirror raspi-config. If it's getting crowded, then a tidy up.

It is an option used by quite a few.
Anyone attaching UART device to the pi, GPS propaby the primary use a look in the forum for help topics shows that. Arduino another iirc.

At the moment it creates problems and you have to tell people to do it manually or use raspi-config.

While I understand the reason for the default, all off as it should be.
And that a few still wish to use a console line.
I believe more whish to attach devices to the pi and use it as a UART port.

It's really only the Zero that is your device using it now, but then the usb gadget mode has probably taken over.

The ZeroW and Pi3 are you most sold and current devices and network connections and remote access.is much improved.

I don't think it should be removed (console options). 

I do think that the serial on and console off should be added, since people use it.

But it's not up to me and I'm only one.

I do believe people can cope with options, even in a clicky GUI world.

But if I had to choose.
At the GUI you want PORT on or PORT off.
You do not need CONSOLE.
As by that point you have a GUI and it is working

Console over UART users will edit the files directly on another device because they have no access to enable it in the first place.

Hope that makes sense, but ask other users.


I work in a school with children, I'm not coming from a tech geek point of view.
(Even if I aspire to be one ;-))

**Comment by bsimmo** [comment]
:-D
Thank you.
