### ISSUE TITLE
Passwords with $ or " don't work when GUI [Change Password] utility is used.

### ISSUE THREAD

**Issue by klricks** [raspberrypi-ui/rc_gui#44]
If $ is first character of password then the GUI change app will not confirm at all. Get invalid password message.
If $ is the last character of PW then it is confirmed and will work normally for login.
If $ appears anywhere else in the PW then the PW is confirmed as valid but does NOT work for login.
Similar issue with "
I do not believe this is a keyboard setting issue.......
Using command line setting **sudo passwd pi** or **passwd pi** works fine with $ or " anywhere in the password.
See forum posts:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=209384#p1294107
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=217795

**Comment by spl237** [comment]
Good find! I wasn't escaping shell characters in the input strings - now fixed. It'll work properly in the next release.
