### ISSUE TITLE
do_vnc logic wrong?  0 should disable not enable, 1 should enabled not disable

### ISSUE THREAD

**Issue by dachshund-digital** [raspberrypi-ui/rc_gui#46]
Testing do_vnc option, it appears to be backwards, 1 should enabled, 0 should be disabled, right?  Well, 0 invokes massive download and enable of the vncserver-x1ll-serviced.service.  Where 1 then disables the same service.

**Comment by spl237** [comment]
Please see the comment on line 28 of rc_gui.c - 

`/* NOTE raspi-config nonint functions obey sh return codes - 0 is in general success / yes / selected, 1 is failed / no / not selected */`

The logic of tests in shell scripts is such that 0 is "true" and 1 is "false". All CLI functions in raspi-config follow this convention.
