### ISSUE TITLE
Toottip for Password change, inconsistency/incorrect.

### ISSUE THREAD

**Issue by bsimmo** [raspberrypi-ui/rc_gui#52]
A user just noticed the tooltip can be incorrect for changing the password.  It always references Pi as the default user (see forum topic)

Solution: It either need to pickup the current logged in user, or easier but maybe less informative, just remove and changed to _Change password for the current user?_
Operation correctly changes the current user, not the default user (Pi) 
(which is raspi-config behaviour)
Comparison to raspi-config correctly picks up the logged in user as the wording.

I think it is this line

```                  <child>
                      <object class="GtkButton" id="button_pw">
                        <property name="label" translatable="yes">Change _Password...</property>
                        <property name="visible">True</property>
                        <property name="can_focus">True</property>
                        <property name="receives_default">True</property>
                        <property name="tooltip_text" translatable="yes">Change password for the default user (pi)</property>
                        <property name="use_underline">True</property>
                      </object>
```

this is the post on the forum.
https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=285859&p=1730350#p1730350

No idea about all the translations that may need to be checked.

**Comment by spl237** [comment]
This is already corrected in the UK English translation file - it is only incorrect for languages which do not have a translation file. Changing the master string is a pain, as it involves changing it in all the submitted translation files, and the default message is actually still correct for the vast majority of users who never change the default user account anyway. So this is a WONTFIX.
