### ISSUE TITLE
Document no interface keywords and magic numbers

### ISSUE THREAD

**Issue by mangelozzi** [raspberrypi-ui/rc_gui#61]
Please consider documenting the no interface (`noint`) mode of raspi-config. 

Many people wish to use it this way: <https://raspberrypi.stackexchange.com/questions/28907/how-could-one-automate-the-raspbian-raspi-config-setup>

**Comment by lurch** [comment]
See https://www.raspberrypi.com/documentation/computers/configuration.html#the-raspi-config-command-line-interface

**Comment by spl237** [comment]
Not relevant to this repo - closing
